<h3 align="center" style="color:blue">Codebasics Python Course: Numpy Exercise</h3>

At **AtliQ**, a software service company, the **HR team** wants to understand how happy employees are with company policies and how long they've been with the company. This survey aims to help HR improve the work environment and keep employees satisfied.

**Data Structure:** Two numpy arrays capture survey results and employee details:

**Employee Details:** Contains Employee ID, Department, and Number of Years with AtliQ.

**Survey Results:** Contains Employee ID and Happiness Score (scaled 1-10).

In [1]:
import numpy as np

# Employee Details: Employee ID, Department, Number of Years with AtliQ
employee_details = np.array([
    [101, 'Sales', 3],  
    [102, 'HR', 5],    
    [103, 'IT', 2],        
    [104, 'Sales', 8],    
    [105, 'IT', 6],      
    [106, 'HR', 4],           
    [107, 'IT', 7],    
    [108, 'Sales', 1], 
    [109, 'HR', 3]          
])

# Survey Results: Employee ID, Happiness Score (1-10)
survey_results = np.array([
    [101, 8],
    [102, 10],
    [103, 9],
    [104, 6],
    [105, 7],
    [106, 8],
    [107, 9],
    [108, 5],
    [109, 7]
])


### Task 1: Merge Arrays

**Scenario:** To streamline analysis, combine the employee details with their survey results.

**Action:** Use ```np.hstack``` to horizontally stack the two arrays.

In [3]:
# write code here
complete_survey_results = np.hstack((employee_details, survey_results[:, 1:]))
print(complete_survey_results)

[['101' 'Sales' '3' '8']
 ['102' 'HR' '5' '10']
 ['103' 'IT' '2' '9']
 ['104' 'Sales' '8' '6']
 ['105' 'IT' '6' '7']
 ['106' 'HR' '4' '8']
 ['107' 'IT' '7' '9']
 ['108' 'Sales' '1' '5']
 ['109' 'HR' '3' '7']]


### Task 2: Print Scores

**Scenario:** HR wants a quick view of all happiness scores to gauge overall employee sentiment.

**Action:** Display all happiness scores from the merged array.

In [5]:
# write code here
happiness_scores = complete_survey_results[:, 3].astype(int)
print(happiness_scores)

[ 8 10  9  6  7  8  9  5  7]


### Task 3: Sort Scores

**Scenario:** HR needs to identify the range of happiness scores to plan specific interventions.

**Action:** Sort and print the happiness scores in ascending order.

In [6]:
# write code here
sorted_scores = np.sort(happiness_scores)
print(sorted_scores)

[ 5  6  7  7  8  8  9  9 10]


### Task 4: Employee Details

**Scenario:** For a meeting, HR needs a list of employees' IDs and departments without other details.

**Action:** Iterate through the array and print each employee's ID and department.

In [7]:
# write code here
for record in complete_survey_results:
    print(f"Employee ID: {record[0]}, Department: {record[1]}")


Employee ID: 101, Department: Sales
Employee ID: 102, Department: HR
Employee ID: 103, Department: IT
Employee ID: 104, Department: Sales
Employee ID: 105, Department: IT
Employee ID: 106, Department: HR
Employee ID: 107, Department: IT
Employee ID: 108, Department: Sales
Employee ID: 109, Department: HR


### Task 5: Happiness Scores

**Scenario:** HR wants to review individual happiness scores to follow up with specific departments or employees.

**Action:** Print the happiness score alongside each employee ID from the merged array.

In [8]:
# write code here
for record in complete_survey_results:
    print(f"Employee ID: {record[0]}, Happiness Score: {record[3]}")


Employee ID: 101, Happiness Score: 8
Employee ID: 102, Happiness Score: 10
Employee ID: 103, Happiness Score: 9
Employee ID: 104, Happiness Score: 6
Employee ID: 105, Happiness Score: 7
Employee ID: 106, Happiness Score: 8
Employee ID: 107, Happiness Score: 9
Employee ID: 108, Happiness Score: 5
Employee ID: 109, Happiness Score: 7


### Task 6: Convert Scores

**Scenario:** For statistical analysis, the HR team needs the happiness scores in a consistent format.

**Action:** Convert the happiness scores to float type using ```astype(float)```.

In [9]:
# write code here
happiness_scores_float = happiness_scores.astype(float)
print(happiness_scores_float)

[ 8. 10.  9.  6.  7.  8.  9.  5.  7.]


### Task 7: Average Score

**Scenario:** To measure the effectiveness of current policies, HR needs the average happiness score.

**Action:** Calculate and print the average happiness score of all employees.

In [10]:
# write code here
average_happiness_score = np.mean(happiness_scores_float)
print(f"Average Happiness Score: {average_happiness_score}")

Average Happiness Score: 7.666666666666667


### Task 8: Unique Departments

**Scenario:** HR is reviewing which departments are represented in the survey to ensure all are included in future plans.

**Action:** Use ```np.unique``` to find and print all unique departments from the employee details.

In [11]:
# first print departments from all the records
departments = complete_survey_results[:, 1]
# write code here

In [13]:
# now print unique departments
unique_departments = np.unique(departments)
print("Unique Departments:", unique_departments)
# write code here

Unique Departments: ['HR' 'IT' 'Sales']


### Task 9: HR Happiness

**Scenario:** HR is conducting a self-assessment to understand how their own department perceives company policies.

**Action:** Calculate and print the average happiness score within the HR department.

In [15]:
# First print all the records in HR department
hr_recors= complete_survey_results[complete_survey_results[:, 1] == 'HR']
print(hr_recors)
# write code here

[['102' 'HR' '5' '10']
 ['106' 'HR' '4' '8']
 ['109' 'HR' '3' '7']]


In [17]:
# Now from these records only print  the happiness score column. Convert that to float using astype(float) function
hr_happiness_scores = hr_recors[:, 3].astype(float)
print(hr_happiness_scores)
# write code here

[10.  8.  7.]


In [18]:
# Take an average of this column using np.mean() function
average_hr_happiness_scores = np.mean(hr_happiness_scores)
print(f"Average Happiness Score in HR Department: {average_hr_happiness_scores}")
# write code here

Average Happiness Score in HR Department: 8.333333333333334
